### ISSUE TITLE
Error Generated on this line in NET 4.0 & 4.7.2

### ISSUE THREAD

**Issue by Jim-Rouse** [queueit/KnownUser.V3.ASPNET#5]
https://github.com/queueit/KnownUser.V3.ASPNET/blob/6de4d14addd170486411238e8424429088db0fe2/Documentation/IntegrationConfigProvider.cs#L68

.NET 4.0 & 4.7.2 generate an errror on this line: The 'User-Agent' header must be modified using the appropriate property or method.\r\nParameter name: name"}  Please retest and verify its functionality.

**Comment by Reza-0** [comment]
Thank you for reporting the issue. It is fixed now.
